### ISSUE TITLE
Please upgrade module ((

### ISSUE THREAD

**Issue by daglex** [WASasquatch/humhub-modules-custom-pages-extended#10]
When the update module for version 0.20.0?

**Comment by Censtudios** [comment]
that would be amazing indeed

**Comment by WASasquatch** [comment]
I have not planned to update the module as I have not been able to use the new composer based version on my Unix server.

**Comment by daglex** [comment]
What's wrong with composer?

**Comment by daglex** [comment]
Now you no longer use HumHub?

**Comment by WebCrew** [comment]
For non command line developers composer, gulp, bower etc etc are not so nice :) so I fully understand WASasquatch. I also love to see a update of the module and also from his awesome designs he has done, hope he will find a way to make it happen :)

Kind regards ;)

**Comment by WASasquatch** [comment]
@daglex I used a Unix server and Composer wouldn't run correctly. Like the process for installation was completed, it said so, but instead of green text, I had yellow text. And upon moving forward to install humhub, it wouldn't work, because the composer files it was suppose to generate were never made. Tried several times, even copying composer files from other installs.

**Comment by ghost** [comment]
No update comming soon ?

**Comment by WASasquatch** [comment]
someone needs to fork.and update. It's not top difficult
