### ISSUE TITLE
Version 0.2.0 Issue

### ISSUE THREAD

**Issue by Vatarus** [WASasquatch/humhub-modules-custom-pages-extended#4]
Hi.

**After switching on the module there is a problem.**
- incorrectly displays the menu (topbar) in the admin panel.
- recording errors in the log

![custompages](https://cloud.githubusercontent.com/assets/3394915/7465145/6a3bb40c-f306-11e4-8622-7aa8850dbf10.png)

**Comment by WASasquatch** [comment]
I cannot reproduce this. What errors do you have installed by chance? I wonder if it's not related to the HumHub Markdown widget having issues rendering in the admin center. It could be do to the 

In any case my copy seems to not have this issue:

<img src="http://i.imgur.com/nrQJKav.png" />

This could be because I have rebuilt a few things and also rebuilt the jquery form actions from scratch with the help of a friend off SO.

**_You can**_ wait until I finish the next update to 0.2.1 which will introduce the no template option and space targeting, or backup old pages and uninstall and reinstall [0.1.3](https://github.com/WASasquatch/humhub-modules-custom-pages-extended/releases/tag/0.1.3)

**Comment by Vatarus** [comment]
Ok. I understood.
But this problem is not just me.
This problem is mentioned here: https://community.humhub.com/wall/perma/content/model/Post/id/1979
Anyway, thanks.

**Comment by WASasquatch** [comment]
Thanks for letting me know. Though I am unsure the front end info is not a error related to my module. Even installing this version, with topbar css error still I don't get that error message. Even gone through 10 pages since before even working on the module on herbsy which still has that version installed, no errors about FrontEndInfo. Errors about the missing elements as I was testing. 

Like I said, downgrade or wait for new patch. I need help from Lucas before releasing next patch as his widget for Space Chooser thingy isn't working.

**Comment by WASasquatch** [comment]
Try updating to [0.2.2](https://github.com/WASasquatch/humhub-modules-custom-pages-extended/releases/tag/0.2.2-2).

Also be sure when creating widgets you keep in mind you are writing in PHP and it is part of the Yii/HumHub stack and must be written within those standards.

**Comment by WASasquatch** [comment]
From what I can tell the issue still remains when using the **mobile** template with the menu. I'm not sure what the issue is honestly. It's using the same logic as before, just making sure only correct pages render in correct areas.

**Comment by Vatarus** [comment]
Thanks!

**Comment by rttmax** [comment]
Tried 0.2.2. Still the same problem.

**Comment by WASasquatch** [comment]
> From what I can tell the issue still remains when using the **mobile** template with the menu. I'm not >sure what the issue is honestly. It's using the same logic as before, just making sure only correct >pages render in correct areas.

**Comment by WASasquatch** [comment]
Update to new patch please https://github.com/WASasquatch/humhub-modules-custom-pages-extended/releases/tag/0.2.3
