### ISSUE TITLE
Custom pages and FFA

### ISSUE THREAD

**Issue by rbraband** [WASasquatch/humhub-modules-custom-pages-extended#6]
Hello, as mentioned I post this bug Report here. I have found that if I use a custom page open to guests that this site is accessible via the direct call - that's as far as we intended.
 But in the top menu the menu item, however, is not displayed. For custom pages that are not visible to guests the menu entry is displayed.
 The bug is that the permission to the page display works, the authorization for the menu does not.

I use custom_pages_extended

**Comment by WASasquatch** [comment]
As I mentioned, you do not have guest mode enabled, and are using guest mode pages. 

When I visit your site, it forced me to the `user/auth/login` page because Guest Mode is not enabled. 

Custom Pages doesn't check to see if Guest Mode is enabled or not. 

**Administration -> Authentication -> First Option**

<img src="http://i.imgur.com/8QAfZzN.png" />

**_otherwise**_ don't set pages for guests when you don't allow guests.

**Comment by WASasquatch** [comment]
https://github.com/WASasquatch/humhub-modules-custom-pages-extended/releases/tag/0.2.4-5
